[package]
name = "coffee"
version = "0.2.0"
edition = "2021"

[profile.release]
strip = "debuginfo"
codegen-units = 1
opt-level = "z"
lto = true

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.19", features = ["derive"] }
coffeeldr = { path = "../" }
env_logger = "0.11.5"
log = "0.4.22"
